// Generated by scripts/build-docs-nav.mjs. Do not edit manually.

import type { DefaultTheme } from 'vitepress'

export const sidebar: DefaultTheme.SidebarItem[] = 
[
  {
    "text": "Introduction",
    "link": "/"
  },
  {
    "text": "Installation",
    "link": "/installation"
  },
  {
    "text": "Usage",
    "link": "/usage"
  },
  {
    "text": "React",
    "link": "/react"
  },
  {
    "text": "Events",
    "link": "/events",
    "items": [
      {
        "text": "Wildcard listener",
        "link": "/events#wildcard-listener"
      },
      {
        "text": "boot",
        "link": "/events#boot"
      },
      {
        "text": "scan",
        "link": "/events#scan"
      },
      {
        "text": "standby",
        "link": "/events#standby"
      },
      {
        "text": "error",
        "link": "/events#error"
      },
      {
        "text": "navigate",
        "link": "/events#navigate"
      },
      {
        "text": "ready",
        "link": "/events#ready"
      },
      {
        "text": "settings",
        "link": "/events#settings"
      }
    ],
    "collapsed": false
  },
  {
    "text": "Migration Guide",
    "link": "/migration",
    "items": [
      {
        "text": "TL;DR",
        "link": "/migration#tldr"
      },
      {
        "text": "1. Replace synchronous isEmbedded checks with the boot event",
        "link": "/migration#1-replace-synchronous-isembedded-checks-with-the-boot-event",
        "items": [
          {
            "text": "Why",
            "link": "/migration#why"
          },
          {
            "text": "Before",
            "link": "/migration#before"
          },
          {
            "text": "After (vanilla)",
            "link": "/migration#after-vanilla"
          },
          {
            "text": "After (React)",
            "link": "/migration#after-react"
          },
          {
            "text": "Notes",
            "link": "/migration#notes"
          }
        ],
        "collapsed": false
      },
      {
        "text": "2. BootPayload is a new exported type",
        "link": "/migration#2-bootpayload-is-a-new-exported-type"
      },
      {
        "text": "3. send() now queues messages until the bridge is ready",
        "link": "/migration#3-send-now-queues-messages-until-the-bridge-is-ready",
        "items": [
          {
            "text": "What changed",
            "link": "/migration#what-changed"
          },
          {
            "text": "Impact",
            "link": "/migration#impact"
          },
          {
            "text": "Things to be aware of",
            "link": "/migration#things-to-be-aware-of"
          }
        ],
        "collapsed": false
      },
      {
        "text": "4. off() now cancels pending poll subscriptions",
        "link": "/migration#4-off-now-cancels-pending-poll-subscriptions",
        "items": [
          {
            "text": "What changed",
            "link": "/migration#what-changed-1"
          },
          {
            "text": "Impact",
            "link": "/migration#impact-1"
          }
        ],
        "collapsed": false
      },
      {
        "text": "5. Bridge poll timeout now emits a console.warn",
        "link": "/migration#5-bridge-poll-timeout-now-emits-a-consolewarn",
        "items": [
          {
            "text": "Impact",
            "link": "/migration#impact-2"
          }
        ],
        "collapsed": false
      },
      {
        "text": "6. Build target moved from esnext to es2018",
        "link": "/migration#6-build-target-moved-from-esnext-to-es2018"
      },
      {
        "text": "7. Removed / breaking changes",
        "link": "/migration#7-removed--breaking-changes"
      }
    ],
    "collapsed": false
  }
]
